name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: SSH TEST
        run: ssh -T git@github.com

      - name: Install dependencies
        working-directory: remix
        run: npm install

      - name: Build project
        working-directory: remix
        run: npm run build

      - name: Deploy
        working-directory: remix
        run: |
          npx gh-pages -d build --repo git@github.com:${{ github.repository }}.git
