name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Debug Git config
        run: git config --list --show-origin

      - name: Install dependencies
        working-directory: remix
        run: npm install

      - name: Build project
        working-directory: remix
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: remix
        run: |
          npx gh-pages -d build --repo git@github.com:${{ github.repository }}.git --user "GitHub Actions <actions@github.com>"

