name: Prod deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:


        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: set up git
          run: |
            git config user.name "Github Actions"
            git config user.email "actions@github.com"

        - name: cache node
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
               ${{ runner.os }}-node-

        - name: npm install
          working-directory: remix
          run: npm install

        - name: npm build
          working-directory: remix
          run : npm run build

        - name: deploy
          working-directory: remix
          env:
            GIT_SSH_COMMAND: sh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no
          run: |
            npx gh-pages -d build --repo git@github.com:${{ github.repository }}.git