name: Prod deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name : npm install
          working-directroy : remix
          uses : npm install

        - name : npm build
          working-directroy : remix
          uses : npm run build

        - name: 📂 Deploy to Server
          env :
              AUTH_TOKEN : ${{ secrets.DEPLOY_TOKEN }}
          run : |
            cd remix
            npm start
            echo "Deploying application"
            curl -H "Authorizition: Bearer $AUTH_TOKEN" https://kimseongho920102.github.io/template