name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: remix
        run: npm install

      - name: Build Project
        working-directory: remix
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"        

      - name: Deploy to GitHub Pages
        working-directory: remix
        run: |
          npx gh-pages -d public --add
          npx gh-pages -d public/build --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
